### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by Perceval-Legaulois** [Linocent/RedLine#20]
Hello Monsieur le Développeur, 
pourriez vous s'il vous plait me rajouter une notification en cas de réservation du véhicule, afin que le client sois avertis une fois qu il aura appuyé sur le bouton de commande. ( Style pop up dans le bas de l’écran ).

Je vous remercie d'avance et reste à votre entière disponibilité afin de vous donnez des renseignements complémentaire.  

Bien à vous 

Perceval Legaulois

**Comment by LeShtroumpf** [comment]
Fix #21
